[package]
# Semantic Versionning is used: https://semver.org/
version = "1.3.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Mead & Hunt","Eric Craft"]

# The title and description fields are primarily for displaying extension info in UI
title = "Mead & Hunt BackPlate"
description="BackPlate that attaches to camera to place images in viewport"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/ericcraft-mh/meadhunt-mesh-backplate"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["kit","meadhunt","mesh","backplate"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview_backplate.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon_backplate.svg"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "meadhunt.mesh.backplate"
